bitbag_sylius_elasticsearch_plugin:
  resource: "@BitBagSyliusElasticsearchPlugin/Resources/config/routing.yml"

# app/config/routing.yml
_bazinga_jstranslation:
  resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

# Symfony 4: config/routes/fos_js_routing.yml
fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"